# The different controllers that are loaded into the controller manager
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    # a typical joint state publisher that publishes the joint states from
    # the HW interface
    lundgren_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    lundgren_position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    lundgren_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

# A joint trajectory controller for the position of the joints.
# It starts an action server called
# lundgren_position_trajectory_controller/follow_joint_trajectory
# which it listens to
lundgren_position_trajectory_controller:
  ros__parameters:
    joints:
      - lundgren_joint_a1
      - lundgren_joint_a2
      - lundgren_joint_a3
      - lundgren_joint_a4
      - lundgren_joint_a5
      - lundgren_joint_a6

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    # The goal set to the action server must contain a goal for all joints.
    # Sending only goals for a few joints will be rejected.
    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

# a forward command controller that will set the position of the robot.
# this is useful for simulations where you can set initial positions,
# but currently we don't find other uses for it.
lundgren_forward_position_controller:
  ros__parameters:
    joints:
      - lundgren_joint_a1
      - lundgren_joint_a2
      - lundgren_joint_a3
      - lundgren_joint_a4
      - lundgren_joint_a5
      - lundgren_joint_a6
    interface_name: position